version: "3.1"
services:
  elasticsearch:
    image: bitnami/elasticsearch:7.9.2
    container_name: es7
    environment:
      - node.name=es7_01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: bitnami/kibana:7.9.2
    container_name: kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - elasticsearch_url=http://localhost:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch