version: '3.4'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --bind 0.0.0.0 --protected-mode no --port 7000 --daemonize no --requirepass 123456 --masterauth 123456 --appendonly yes --logfile "redis.log" --dir ./
    ports:
        - 7000:7000
    volumes:
        - ./redis/data7000:/data

  slave1:
    image: redis
    container_name: redis-slave1
    restart: always
    command: redis-server --bind 0.0.0.0 --protected-mode no --slaveof 192.168.31.53 7000 --port 7001 --daemonize no --requirepass 123456 --masterauth 123456 --appendonly yes --logfile "redis.log" --dir ./
    ports:
        - 7001:7001
    volumes:
        - ./redis/data7001:/data

  slave2:
    image: redis
    container_name: redis-slave2
    restart: always
    command: redis-server --bind 0.0.0.0 --protected-mode no --slaveof 192.168.31.53 7000 --port 7002 --daemonize no --requirepass 123456 --masterauth 123456 --appendonly yes --logfile "redis.log" --dir ./
    ports:
        - 7002:7002
    volumes:
        - ./redis/data7002:/data
  sentinel1:
    image: redis
    container_name: sentinel1
    restart: always
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
        - 26379:26379
    volumes:
        - ./sentinel/sentinel26379:/data
        - ./sentinel26379.conf:/etc/redis/sentinel.conf
        
  sentinel2:
    image: redis
    container_name: sentinel2
    restart: always
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
        - 26380:26380
    volumes:
        - ./sentinel/sentinel26380:/data
        - ./sentinel26380.conf:/etc/redis/sentinel.conf
        
  sentinel3:
    image: redis
    container_name: sentinel3
    restart: always
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
        - 26381:26381
    volumes:
        - ./sentinel/sentinel26381:/data
        - ./sentinel26381.conf:/etc/redis/sentinel.conf
        
